name: Extras

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-vscode-yarg:
    name: vscode-yarg (tools/build-vscode-yarg.sh)
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
    
      - name: Install npm
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install VSCode dependencies
        run: npm install -g @vscode/vsce

      - name: Build VSCode Extension
        run: |
          pushd vscode-yarg
          vsce package

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vscode-yarg-extension
          path: vscode-yarg/*.vsix

  build-xcode:
    name: Xcode (tools/build-xcode.sh)
    runs-on: macos-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21.4'
          cache: false
    
      - name: Build hostyarg
        run: |
          cd hostyarg
          go build -o ../bin/hostyarg .

      - name: Build Xcode project
        run: |
          cd cyarg
          cmake --preset xcode-host
          cmake --build build/xcode-host

      - name: Run test suite
        run: ./bin/hostyarg runtests -tests "yarg/test" -interpreter "cyarg/build/xcode-host/Debug/cyarg"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: yarg-lang-macos-xcode
          path: |
            bin/hostyarg
            cyarg/build/xcode-host/cyarg
